# ############################################################################
# Model: Tokenized TTS (WhisperSpeech-inspired)
# Authors:  Artem Ploujnikov
# ############################################################################

experiment_name: valle/discrete_ssl
# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 74443
__set_seed: !apply:torch.manual_seed [!ref <seed>]
run_name: !PLACEHOLDER

# Model Type
ssl_model_type: wavlm
representation_mode: discrete
output_folder: !ref results/tokotron/<experiment_name>/<ssl_model_type>/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
testing: True # If set to True, the test evlaution is done, otherwise skipped.


# Data files
data_folder: !PLACEHOLDER
cached_data_folder: !PLACEHOLDER
prepare_save_folder: !ref <cached_data_folder>
pretrained_model_save_folder: !ref <prepare_save_folder>
vocoder_model_name: !ref unithifigan-dasb-<ssl_model_type>-discrete
vocoder_model_path: !ref <pretrained_model_save_folder>/<vocoder_model_name>
prepare_archive_path: null
prepare_skip_ignore_folders: False
train_json: !ref <prepare_save_folder>/train.json
valid_json: !ref <prepare_save_folder>/valid.json
test_json: !ref <prepare_save_folder>/test.json
frozen_split_path: null
sample_path: null
progress_folder: !ref <output_folder>/progress
progress_current: !ref <progress_folder>/current
progress_meta: !ref <progress_folder>/meta.yaml
num_audio_samples: 32
samples_interval: 5
tokens_folder: !PLACEHOLDER
tokens_loader: !new:utils.tokens.TokensLoader
    data_path: !ref <tokens_folder>
freeze_token_model: True
token_model_src: !apply:speechbrain.utils.hparams.choice
    value: !ref <ssl_model_type>
    choices:
        wavlm: microsoft/wavlm-large
        hubert: facebook/hubert-large-ll60k
        wav2vec2: facebook/wav2vec2-large-960h-lv60-self
g2p_src: speechbrain/soundchoice-g2p
token_model_kmeans_src: poonehmousavi/SSL_Quantization
kmeans_cache_dir: !ref <save_folder>/kmeans_checkpoint
kmeans_dataset: LibriSpeech
vocoder_repo_id: !apply:speechbrain.utils.hparams.choice
    value: !ref <ssl_model_type>
    choices:
        hubert: speechbrain/hifigan-hubert-k1000-LibriTTS
        wavlm: speechbrain/hifigan-wavlm-k1000-LibriTTS
        wav2vec2: speechbrain/hifigan-wav2vec2-k1000-LibriTTS

ssl_model_layers: [1, 3, 7, 12, 18, 23]
token_model_layers: !ref <ssl_model_layers>
token_offset: 1
spk_emb_src: speechbrain/spkrec-ecapa-voxceleb-mel-spec
use_spk_emb: False
splits: ["train", "valid", "test"]
split_ratio: [90, 5, 5]
ckpt_interval_minutes: 30 # save checkpoint every N min

# Training parameters
input: text
number_of_epochs: 50
batch_size: 16 
grad_accumulation_factor: 1
max_grad_norm: 0.01
sorting: random
num_workers: 4
skip_prep: False
overfit_test: False
overfit_test_sample_count: !ref <batch_size>
overfit_test_epoch_data_count: 1000

# index
pad_index: 0
bos_index: 1
eos_index: 2
eot_index: 3
special_tokens: ["<bos>", "<eos>", "<eot>"]
special_num_tokens: 4

# stages related parameters
lr: 0.0005 # @orion_step1: --lr~"loguniform(0.00001,0.005)"
lr_warmup_steps: 10000
lr_annealing_mode: step

# Feature parameters
sample_rate: 22050
model_sample_rate: 16000
max_audio_length: 2000
text_max_length: 500
n_ctx: !ref <max_audio_length> + <text_max_length>
infer_max_audio_length: !ref <max_audio_length>
debug_infer_max_audio_length: 10

# Label encoder
label_encoder: !new:speechbrain.dataio.encoder.TextEncoder
token_list_file_text: char_en.txt
token_list_file_phn: arpabet.txt
token_list_file: !apply:speechbrain.utils.hparams.choice
    value: !ref <input>
    choices:
        text: !ref <token_list_file_text>
        phonemes: !ref <token_list_file_phn>

# Token model (pretrained)
ssl_model: !apply:speechbrain.utils.hparams.choice
    value: !ref <ssl_model_type>
    choices:
        wavlm: !new:speechbrain.lobes.models.huggingface_transformers.wavlm.WavLM
            source: !ref <token_model_src>
            save_path: !ref <pretrained_model_save_folder>
            freeze: !ref <freeze_token_model>
            output_all_hiddens: True
        hubert: !new:speechbrain.lobes.models.huggingface_transformers.hubert.HuBERT
            source: !ref <token_model_src>
            save_path: !ref <pretrained_model_save_folder>
            freeze: !ref <freeze_token_model>
            output_all_hiddens: True
        wav2vec2: !new:speechbrain.lobes.models.huggingface_transformers.wav2vec2.Wav2Vec2
            source: !ref <token_model_src>
            save_path: !ref <pretrained_model_save_folder>
            freeze: !ref <freeze_token_model>
            output_all_hiddens: True
spk_emb_model: !name:speechbrain.inference.encoders.MelSpectrogramEncoder.from_hparams
    source: !ref <spk_emb_src>
    savedir: !ref <pretrained_model_save_folder>/ecapa

# Dataloader options
train_dataloader_opts:
    batch_size: !ref <batch_size>
    shuffle: True
    num_workers: !ref <num_workers>
    collate_fn: !name:speechbrain.dataio.batch.PaddedBatch
        padding_kwargs:
            value: !ref <pad_index>
valid_dataloader_opts:
    batch_size: !ref <batch_size>
    num_workers: !ref <num_workers>
    collate_fn: !name:speechbrain.dataio.batch.PaddedBatch
        padding_kwargs:
            value: !ref <pad_index>
test_dataloader_opts:
    batch_size: 1
    num_workers: !ref <num_workers>
    collate_fn: !name:speechbrain.dataio.batch.PaddedBatch
        padding_kwargs:
            value: !ref <pad_index>
sample_dataloader_opts:
    batch_size: !ref <batch_size>
    num_workers: !ref <num_workers>
    collate_fn: !name:speechbrain.dataio.batch.PaddedBatch
        padding_kwargs:
            value: !ref <pad_index>
token_model_kwargs:
    SSL_layers: !ref <token_model_layers>

####################### Model parameters ###########################
# Transformer
d_model: 1024
share_emb: False
qk_norm: True
nhead: 16
num_layers_ar: 12
num_layers_nar: 12
dropout: 0.2
vocab_size: 1000
audio_emb_size: 1024
audio_emb_freeze: False
audio_emb_pretrained: False
audio_emb_lr: 0.00001
audio_emb_weight_decay: 0.001
text_num_tokens: 39
phn_num_tokens: 52
input_num_tokens: !apply:speechbrain.utils.hparams.choice
    value: !ref <input>
    choices:
        text: !ref <text_num_tokens>
        phonemes: !ref <phn_num_tokens>

model_vocab_size: !apply:speechbrain.utils.hparams.choice
    value: !ref <input>
    choices:
        text: !ref <text_num_tokens> + (<vocab_size> * <audio_tokens_per_step>) + <special_num_tokens>
        phonemes: !ref <phn_num_tokens> + (<vocab_size> * <audio_tokens_per_step>) + <special_num_tokens>

audio_token_shift: !apply:speechbrain.utils.hparams.choice
    value: !ref <input>
    choices:
        text: !ref <text_num_tokens> +  <special_num_tokens>
        phonemes: !ref <phn_num_tokens> + <special_num_tokens>

audio_tokens_per_step: 6

############################## models ################################

model: !new:model.valle.ValleLM # yamllint disable-line rule:line-length
    vocab_size: !ref <model_vocab_size>
    nq: !ref <audio_tokens_per_step>
    att_unit: !ref <d_model>
    head: !ref <nhead>
    ar_layer: !ref <num_layers_ar>
    nar_layer: !ref <num_layers_nar>
    n_ctx: !ref <n_ctx>
    dropout: !ref <dropout>
    share_emb: !ref <share_emb>
    qk_norm: !ref <qk_norm>

inference_opts: !name:model.valle.SpeechLMInferenceOptions
    start: !ref <bos_index>
    eos: !ref <eos_index>
    minlenratio: 1.0
    maxlenratio: !ref <max_length_ratio>
    nq: !ref <audio_tokens_per_step>

tokenizer: !new:utils.tokenizer_interface.DiscreteSSLTokenizer
    save_path: !ref <kmeans_cache_dir>
    ssl_model: !ref <ssl_model>
    vocoder_repo_id: !ref <vocoder_repo_id>
    kmeans_dataset: !ref <kmeans_dataset>
    num_clusters: !ref <vocab_size>

modules:
    model: !ref <model>
    tokenizer: !ref <tokenizer>

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>


compute_cost: !name:model.valle.masked_nll_loss

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True


lr_annealing: !new:model.Tokotron.TargetedNoamScheduler
    lr_initial: [!ref <lr>, !ref <audio_emb_lr>]
    n_warmup_steps: !ref <lr_warmup_steps>
    param_group: 0

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        lr_scheduler: !ref <lr_annealing>
        counter: !ref <epoch_counter>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
